home:
    path: /
    controller: App\Controller\HomeController::index
about : 
    path : /about
    controller: App\Controller\AboutController::index
contact : 
    path : /contact
    controller: App\Controller\ContactController::index

